# -*- coding: utf-8 -*-
"""Despliegue_proyecto_clasificación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WeKbC4nVeIN3sGrG342ZRmuWutysWP1Q

#Despliegue


*   Cargamos el modelo
*   Cargamos los datos futuros
*   Preparar los datos futuros
*   Aplicamos el modelo para la predicción
"""

#cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle

filename = 'modelo-class.pkl'

modelo, label_encoder, variables, min_max_scaler = pickle.load(
    open(filename, 'rb')
)

#Cargamos los datos futuros
#data = pd.read_csv("Logistico-datos-futuros.csv")
#data.head()

#Interfaz gráfica

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title(
    'Predicción de retrasos y evaluación de riesgo en operaciones logísticas del sur de California'
)

Mes = st.selectbox(
    'Mes',
    ["enero","febrero","marzo","abril","mayo",
     "junio","julio","agosto","septiembre",
     "octubre","noviembre","diciembre"]
)

Da = st.selectbox(
    'Da',
    ["lunes","martes","miércoles",
     "jueves","viernes","sábado","domingo"]
)

warehouse_inventory_level = st.slider(
    'warehouse_inventory_level',
    min_value=0,
    max_value=1000,
    value=20,
    step=1
)

shipping_costs = st.slider(
    'shipping_costs',
    min_value=100,
    max_value=1000,
    value=200,
    step=1
)

supplier_reliability_score = st.slider(
    'supplier_reliability_score',
    min_value=0.0,
    max_value=1.0,
    value=0.5,
    step=0.01
)

lead_time_days = st.slider(
    'lead_time_days',
    min_value=0,
    max_value=15,
    value=5,
    step=1
)

historical_demand = st.slider(
    'historical_demand',
    min_value=0,
    max_value=100,
    value=20,
    step=1
)

route_risk_level = st.slider(
    'route_risk_level',
    min_value=0,
    max_value=10,
    value=5,
    step=1
)

driver_behavior_score = st.slider(
    'driver_behavior_score',
    min_value=0.0,
    max_value=1.0,
    value=0.5,
    step=0.01
)

datos = [[
    Mes,
    Da,
    warehouse_inventory_level,
    shipping_costs,
    supplier_reliability_score,
    lead_time_days,
    historical_demand,
    route_risk_level,
    driver_behavior_score
]]

data_preparada = pd.DataFrame(
    datos,
    columns=[
        'Mes',
        'Da',
        'warehouse_inventory_level',
        'shipping_costs',
        'supplier_reliability_score',
        'lead_time_days',
        'historical_demand',
        'route_risk_level',
        'driver_behavior_score'
    ]
)

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['Mes','Da'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
data_preparada[['warehouse_inventory_level','shipping_costs','lead_time_days','historical_demand','route_risk_level']]= min_max_scaler.transform(data_preparada[['warehouse_inventory_level','shipping_costs','lead_time_days','historical_demand','route_risk_level']])
data_preparada.head()

"""***#Predicciones***"""

#Hacemos la predicción con la red

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

#Recordar medida de error del modelo
st.warning("El modelo tiene un recal del 78% en high risk, 39% en low risk, 15% en moderate risk ")